# Generated by Django 2.0.1 on 2018-02-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_pages', '0003_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
