# Generated by Django 2.0.1 on 2018-01-31 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_pages', '0005_auto_20180131_1537'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcement_Images',
        ),
        migrations.AddField(
            model_name='announcements',
            name='image',
            field=models.ImageField(null=True, upload_to='announcements/'),
        ),
    ]
