# Generated by Django 2.0.1 on 2018-01-31 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('private_pages', '0006_auto_20180131_1546'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Announcements',
            new_name='Announcement',
        ),
    ]
