# Generated by Django 2.0.1 on 2018-01-31 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('private_pages', '0007_auto_20180131_2305'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Announcement',
            new_name='Announcements',
        ),
    ]
