# Generated by Django 2.0.1 on 2018-02-24 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('private_pages', '0009_auto_20180201_0231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleries',
            name='creator_full_name',
        ),
        migrations.RemoveField(
            model_name='galleries',
            name='creator_nickname',
        ),
        migrations.RemoveField(
            model_name='galleries',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='galleries',
            name='shares',
        ),
        migrations.AlterField(
            model_name='announcements',
            name='created_by',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='creator_full_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='creator_nickname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='announcements/'),
        ),
        migrations.AlterField(
            model_name='cloudstorage',
            name='created_by',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='cloudstorage',
            name='creator_full_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cloudstorage',
            name='creator_nickname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='galleries',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gallery_access',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='private_pages.Galleries'),
        ),
        migrations.AlterField(
            model_name='gallery_images',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='private_pages.Galleries'),
        ),
    ]
