# Generated by Django 2.0.1 on 2018-02-25 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('private_pages', '0010_auto_20180224_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery_images',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='gallery_images',
            name='shares',
        ),
    ]
