# Generated by Django 2.0.1 on 2018-02-25 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('private_pages', '0012_auto_20180225_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery_access',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_access', to='private_pages.Galleries'),
        ),
    ]
