# Generated by Django 2.0.1 on 2018-02-26 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('private_pages', '0014_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
