# Generated by Django 2.0.1 on 2018-02-27 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_pages', '0017_auto_20180227_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='dummy@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
