# Generated by Django 2.0.1 on 2018-02-27 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_pages', '0019_auto_20180227_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default=2, upload_to='profiles/'),
            preserve_default=False,
        ),
    ]
