# Generated by Django 2.0.1 on 2018-01-28 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
